language: android
env:
  global:
    - COVERALLS_REPO_TOKEN=BUA8U7NyJVhXb6VKGjfSVotuEG5SW2Jj5
    - CODECOV_TOKEN="8942fd6b-2782-45b7-8842-aa97ca17d230"

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - platform-tools
    - extra-android-support # because I'm use support library
    - extra-android-m2repository # because I'm use support library
  licenses:
    - '.+'
language: java

jdk:
  - oraclejdk8

install: true

before_script:
    - chmod +x ./gradlew

script:
  - ./gradlew check
  - ./gradlew build cobertura coveralls
	
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew cobertura coveralls
