language: android
jdk: oraclejdk8
before_install:
  # Download SDK
  - echo yes | sdkmanager "tools" &>/dev/null
  - echo yes | sdkmanager "platform-tools" &>/dev/null
  - echo yes | sdkmanager "build-tools;28.0.2" &>/dev/null
  - echo yes | sdkmanager "platforms;android-26" &>/dev/null
  # Update remaining dependencies and accept licenses
  - echo yes | sdkmanager --update &>/dev/null
  - echo yes | sdkmanager --licenses &>/dev/null


